# Generated by Django 3.2.4 on 2022-09-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eva', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(db_column='respuesta', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_relacionada_ciclo', to='eva.ciclo')),
            ],
            options={
                'db_table': 'analisis_pregunta',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_column='nombre', max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_relacionada', to='eva.ciclo')),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='AnalisisRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(db_column='respuesta', max_length=250)),
                ('username', models.IntegerField(default=0)),
                ('email', models.CharField(db_column='email', max_length=250)),
                ('nombres', models.CharField(db_column='nombres', max_length=250)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=250)),
                ('nivel', models.CharField(db_column='nivel', max_length=250)),
                ('ciclo', models.CharField(db_column='ciclo', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_relacionada', to='analisis.analisispregunta')),
            ],
            options={
                'db_table': 'analisis_respuestas',
            },
        ),
        migrations.AddField(
            model_name='analisispregunta',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_relacionada', to='analisis.nivel'),
        ),
    ]
