# Generated by Django 3.1.13 on 2021-12-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_asesor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=25)),
                ('Carrera', models.ForeignKey(db_column='id', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='conf.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Cabecera_Crono',
            fields=[
                ('Id_Cabecera_Crono', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Dia_Creación', models.DateTimeField(auto_now_add=True)),
                ('Estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('Id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=200)),
                ('Fecha_de_Apertura', models.DateTimeField()),
                ('Fecha_fin', models.DateTimeField()),
                ('Carrera', models.ForeignKey(db_column='id', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='conf.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Académico',
            fields=[
                ('id_academico', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=60)),
                ('Detalle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id_recursos', models.AutoField(primary_key=True, serialize=False)),
                ('Tiempo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombramiento', models.CharField(max_length=25)),
                ('Carrera', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='conf.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='registro_historicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.cabecera_crono')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id_ob', models.AutoField(primary_key=True, serialize=False)),
                ('Observaciones', models.TextField()),
                ('Nombre_Cabecera', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.cabecera_crono')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='asesor.cabecera_crono')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docentes', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=30)),
                ('Carrera', models.ForeignKey(db_column='id', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='conf.carrera')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesor.cursos')),
                ('Nivel_Académico', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='asesor.nivel_académico')),
                ('Titulo', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='asesor.titulos')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Asesor',
            fields=[
                ('id_curso_asesor', models.AutoField(primary_key=True, serialize=False)),
                ('Relacion', models.CharField(max_length=200)),
                ('Asesor', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.asesor')),
                ('Curso', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.cursos')),
                ('Estudiante', models.ManyToManyField(blank=True, help_text='Ctrl para elegir varios Servicios', to='asesor.Docentes')),
            ],
        ),
        migrations.AddField(
            model_name='cabecera_crono',
            name='Periodo',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.periodo'),
        ),
        migrations.AddField(
            model_name='cabecera_crono',
            name='Relación',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='asesor.curso_asesor'),
        ),
        migrations.AddField(
            model_name='cabecera_crono',
            name='Tiempo',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.recursos'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Nivel_Académico',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='asesor.nivel_académico'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Titulo',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='asesor.titulos'),
        ),
    ]
