# Generated by Django 3.1.13 on 2022-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion_Modulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('modulo_id', models.IntegerField()),
                ('nombre_modulo', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
                ('valoracion', models.IntegerField()),
            ],
        ),
    ]
