# Generated by Django 3.1.13 on 2022-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valoration_course_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('score_course', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='valoration_module_estudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('module_id', models.IntegerField()),
                ('module_name', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_id', models.IntegerField()),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('score_activity', models.IntegerField()),
            ],
        ),
    ]
