# Generated by Django 3.1.13 on 2022-02-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0002_valoracion_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_value', models.CharField(max_length=200)),
                ('return_value', models.IntegerField()),
            ],
        ),
    ]
