# Generated by Django 3.1.13 on 2022-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0002_valoration_course_student_valoration_module_estudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoration_course_student',
            name='score_course',
            field=models.FloatField(),
        ),
    ]
