# Generated by Django 3.1.13 on 2022-02-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0003_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='val_activity_module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('nombre_modulo', models.CharField(max_length=200)),
                ('nombre_actividad', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
                ('valoracion', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.valoracion')),
            ],
        ),
    ]
