# Generated by Django 3.1.13 on 2022-03-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0003_auto_20220224_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo_academico',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesor.periodo')),
            ],
        ),
    ]
