# Generated by Django 3.1.13 on 2022-02-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0004_val_activity_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='cronograma_estudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_dias', models.SmallIntegerField(default=1, verbose_name='Cantidad de dias segun actividad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre_curso', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='asesor.cursos')),
            ],
        ),
    ]
