# Generated by Django 3.1.13 on 2022-03-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0004_periodo_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoration_course_student',
            name='academic_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
