version: "3.9"

services:
  db:
    image: postgres
    container_name: secoed_pg
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_secoed
      - POSTGRES_USER=secoed
      - POSTGRES_PASSWORD=secoed2021
    ports:
      - "5434:5435"
    expose:
      - "5434"
  web:
    build: .
    container_name: secoed_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8086:8000"
    depends_on:
      - db
    expose:
      - "8086"