version: "3.9"

services:
  db:
    image: postgres
    container_name: pg_secoed
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_secoed
      - POSTGRES_USER=secoed
      - POSTGRES_PASSWORD=secoed@2021
    ports:
      - 5434:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: secoed_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
