version: "3.9"

services:
  db:
    image: postgres
    container_name: pg_secoed
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: >
      sh -c 'python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000'
    container_name: secoed_web
    volumes:
      - .:/code
    ports:
      - "8086:8000"
    env_file:
      - ./.env
    depends_on:
      - db