version: "3.9"

services:
  db:
    image: postgres
    container_name: pg_secoed
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8086
    container_name: secoed_web
    volumes:
      - .:/code
    ports:
      - "8086:8086"
    depends_on:
      - db