version: "3.9"
   
services:
  web:
    build: .
    container_name: secoed_web
    command:
     - python manage.py runserver 0.0.0.0:8000
     - python manage.py migrate
    volumes:
      - .:/code
    ports:
      - "8000:8000"