# Generated by Django 3.2.15 on 2022-08-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('idcarpeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fechacreacion', models.DateField(max_length=10, null=True, verbose_name='Fecha de creacion')),
                ('fechamodificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('idarchivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('archivo', models.FileField(null=True, upload_to='media', verbose_name='Archivo')),
                ('fechacreacion', models.DateField(max_length=10, null=True, verbose_name='Fecha de creacion')),
                ('fechamodificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.carpeta')),
            ],
        ),
    ]
