# Generated by Django 3.2.15 on 2022-08-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
