# Generated by Django 3.2.15 on 2022-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_delete_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
