# Generated by Django 3.2.15 on 2022-08-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_auto_20220818_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
