# Generated by Django 3.2.15 on 2022-08-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_alter_carpeta_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('idarchivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('archivo', models.FileField(null=True, upload_to='media/repositorio_archivos', verbose_name='Archivo')),
                ('descripcion', models.TextField(null=True)),
                ('fechacreacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('fechamodificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.carpeta')),
            ],
        ),
    ]
