# Generated by Django 3.2.15 on 2022-08-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0006_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='repositorio_archivos', verbose_name='Archivo'),
        ),
    ]
