# Generated by Django 3.2.15 on 2022-08-28 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.carpeta'),
        ),
    ]
