# Generated by Django 3.2.15 on 2022-09-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0009_alter_archivo_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
