# Generated by Django 3.2.15 on 2022-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0010_carpeta_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='ruta',
            field=models.TextField(null=True),
        ),
    ]
