# Generated by Django 3.2.4 on 2023-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0012_carpeta_nombre_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(max_length=7000, upload_to='repositorio_archivos', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='nombre_anterior',
            field=models.TextField(null=True),
        ),
    ]
