# Generated by Django 3.1.13 on 2021-12-01 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('identificacion', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion domiciliaria')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('imagen', models.ImageField(max_length=200, null=True, upload_to='user/', verbose_name='Imagen de perfil')),
                ('moodle_user', models.IntegerField(null=True, verbose_name='Id del usuario de moodle')),
                ('rol_moodle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.rolmoodle')),
            ],
            options={
                'db_table': 'conf_user',
            },
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.rol')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conf_rol_user',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(through='authentication.RolUser', to='conf.Rol'),
        ),
    ]
