# Generated by Django 3.1.13 on 2022-02-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaforizacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.SmallIntegerField(default=1)),
                ('criterio', models.CharField(max_length=200)),
                ('porcentaje_aprobacion', models.IntegerField(default=0)),
                ('semaforo', models.ImageField(upload_to='images/semaforos')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
