# Generated by Django 3.1.13 on 2022-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_semaforizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaforizacion',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
