# Generated by Django 3.1.13 on 2021-12-01 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
                ('career', models.ForeignKey(db_column='carrera', on_delete=django.db.models.deletion.CASCADE, to='conf.carrera')),
                ('docente', models.ForeignKey(db_column='docente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pt_area_conocimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
            ],
            options={
                'db_table': 'pt_categoria',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_column='es_activo', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
            ],
            options={
                'db_table': 'pt_ciclo',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMoodle', models.IntegerField(db_column='id_moodle')),
                ('sortName', models.CharField(db_column='nombre_corto', max_length=150)),
                ('fullName', models.CharField(db_column='nombre_completo', max_length=150)),
                ('categoryName', models.CharField(db_column='categoria', max_length=150)),
                ('image', models.ImageField(db_column='imagen', default='', max_length=300, upload_to='images/eva/')),
                ('startDate', models.DateTimeField(db_column='fecha_inicio')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
            ],
            options={
                'db_table': 'pt_curso',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
                ('area', models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.CASCADE, to='eva.areasconocimiento')),
                ('teacher', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pt_materia',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=20, unique=True)),
                ('description', models.CharField(db_column='Descripcion', max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
            ],
            options={
                'db_table': 'pt_parametro',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField(db_column='docente')),
                ('cycle', models.IntegerField(db_column='ciclo')),
                ('type_evaluation', models.IntegerField(db_column='typo_evaluacion')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
            ],
            options={
                'db_table': 'pt_respuesta',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=60, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación del tipo de Evaluación')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
            ],
            options={
                'db_table': 'pt_tipo',
            },
        ),
        migrations.CreateModel(
            name='ResultadoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(db_column='ciclo')),
                ('user', models.IntegerField(db_column='docente')),
                ('coevaluator', models.CharField(blank=True, db_column='coevaluador', max_length=10, null=True)),
                ('auto_result_Tic', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('auto_result_Did', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('auto_result_Ped', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Total_Proceso_Auto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('coe_result_Tic', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('coe_result_Did', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('coe_result_Ped', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Total_Proceso_Coe', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Total_Proceso', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Registra la fecha de creación de un valor')),
                ('answer', models.ForeignKey(db_column='respuesta', on_delete=django.db.models.deletion.CASCADE, to='eva.respuesta')),
            ],
            options={
                'db_table': 'pt_resultado_proceso',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='titulo', help_text='registra el titulo de la pregunta', max_length=1000)),
                ('description', models.CharField(db_column='description', help_text='registra la descripción de la pregunta', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
                ('category', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, to='eva.categoria')),
                ('type', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.CASCADE, to='eva.tipo')),
            ],
            options={
                'db_table': 'pt_pregunta',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=5, unique=True)),
                ('value', models.DecimalField(db_column='valor', decimal_places=2, default=0, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.parametro', verbose_name='parametro_id')),
            ],
            options={
                'db_table': 'pt_parametro_general',
            },
        ),
        migrations.CreateModel(
            name='MateriaDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion', help_text='Fecha de edición del registro')),
                ('docente', models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(db_column='materia', on_delete=django.db.models.deletion.CASCADE, to='eva.materia')),
            ],
            options={
                'db_table': 'pt_materia_docente',
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(db_column='categoria')),
                ('question', models.IntegerField(db_column='pregunta')),
                ('parameter', models.IntegerField(db_column='indicador')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', help_text='Registra la fecha de creación de un valor')),
                ('answer', models.ForeignKey(db_column='respuesta', on_delete=django.db.models.deletion.CASCADE, to='eva.respuesta')),
            ],
            options={
                'db_table': 'pt_detalle_respuesta',
            },
        ),
    ]
