# Generated by Django 3.1.13 on 2021-12-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000)),
                ('orden', models.IntegerField(default=0)),
                ('icon', models.TextField(max_length=1000, null=True)),
                ('href', models.TextField(max_length=1000, null=True)),
                ('url', models.TextField(max_length=1000, null=True)),
                ('key', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000)),
                ('orden', models.IntegerField(default=0)),
                ('icon', models.TextField(max_length=1000)),
                ('key', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolMoodle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(null=True)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'conf_rol_moodle',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('telefono', models.TextField(max_length=1000, null=True)),
                ('correo', models.TextField(max_length=1000, null=True)),
                ('direccion', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.menu')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.rol')),
            ],
            options={
                'db_table': 'conf_rol_menu',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='modulo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.modulo'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(through='conf.RolMenu', to='conf.Rol'),
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('telefono', models.TextField(max_length=1000, null=True)),
                ('correo', models.TextField(max_length=1000, null=True)),
                ('direccion', models.TextField(max_length=1000, null=True)),
                ('universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('telefono', models.TextField(max_length=1000, null=True)),
                ('correo', models.TextField(max_length=1000, null=True)),
                ('direccion', models.TextField(max_length=1000, null=True)),
                ('responsable', models.TextField(max_length=1000, null=True)),
                ('telf_responsable', models.TextField(max_length=1000, null=True)),
                ('correo_responsable', models.TextField(max_length=1000, null=True)),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.facultad')),
            ],
        ),
    ]
